apiVersion: v1
name: longhorn
<<<<<<< HEAD
version: 1.2.1-rc2
appVersion: v1.2.1-rc2
kubeVersion: ">=1.18.0-0"
=======
version: 1.1.3-rc2
appVersion: v1.1.3-rc2
kubeVersion: ">=v1.16.0-r0 <v1.22.0-r0"
>>>>>>> 5f22f2ab7ce9afaf5818d9fe3908fc57c203ee21
description: Longhorn is a distributed block storage system for Kubernetes.
keywords:
- longhorn
- storage
- distributed
- block
- device
- iscsi
- nfs
home: https://github.com/longhorn/longhorn
sources:
- https://github.com/longhorn/longhorn
- https://github.com/longhorn/longhorn-engine
- https://github.com/longhorn/longhorn-instance-manager
- https://github.com/longhorn/longhorn-share-manager
- https://github.com/longhorn/longhorn-manager
- https://github.com/longhorn/longhorn-ui
- https://github.com/longhorn/longhorn-tests
- https://github.com/longhorn/backing-image-manager
maintainers:
- name: Longhorn maintainers
  email: maintainers@longhorn.io
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/longhorn/icon/color/longhorn-icon-color.png
